In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from statsmodels.api import OLS

df = pd.read_csv("https://raw.githubusercontent.com/diogenesjusto/FIAP/master/Gradua%C3%A7%C3%A3o/dados/pib.csv")
df.head()

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi3,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03
2,3,mar/04,110.43,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70
3,4,abr/04,106.77,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,102.05,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93

In [ ]:
# Separação de bases de treino e teste
treino = df.iloc[0:125]
teste  = df.iloc[126:137]
treino.head()

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi3,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12
0,1,jan/04,103.09,109.19,108.67,109.08,102.84,114.27,105.38,127.49,...,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03,100.00
1,2,fev/04,102.05,95.65,104.52,97.63,90.76,109.83,94.99,96.60,...,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70,100.03
2,3,mar/04,110.43,91.69,125.53,99.26,89.78,133.24,99.43,83.79,...,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17,101.70
3,4,abr/04,106.77,95.36,118.34,100.49,94.58,123.55,101.02,91.79,...,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93,101.17
4,5,mai/04,108.08,92.47,121.49,98.96,91.34,128.32,99.55,85.73,...,102.05,103.09,103.91,104.10,106.27,104.52,102.59,102.24,99.96,101.93

In [ ]:
teste.head()

,Unnamed: 0,ANO_MES,PIB,BRL,BRP,BRT,SLP,SPP,SPT,PRL,...,PIBi3,PIBi4,PIBi5,PIBi6,PIBi7,PIBi8,PIBi9,PIBi10,PIBi11,PIBi12
126,127,jul/14,154.34,150.55,165.58,153.80,154.34,181.79,159.98,160.34,...,150.92,151.44,148.92,151.43,150.30,153.20,156.88,153.50,156.98,156.05
127,128,ago/14,154.75,157.10,165.43,158.42,162.93,183.95,167.07,157.24,...,154.49,150.92,151.44,148.92,151.43,150.30,153.20,156.88,153.50,156.98
128,129,set/14,154.04,150.24,165.35,153.34,155.18,184.73,161.62,153.14,...,148.92,154.49,150.92,151.44,148.92,151.43,150.30,153.20,156.88,153.50
129,130,out/14,156.65,158.52,174.27,161.88,164.71,195.26,170.61,159.38,...,154.34,148.92,154.49,150.92,151.44,148.92,151.43,150.30,153.20,156.88
130,131,nov/14,151.46,157.98,159.69,157.81,163.41,177.27,165.67,161.48,...,154.75,154.34,148.92,154.49,150.92,151.44,148.92,151.43,150.30,153.20

Warning: Total number of columns (38) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
# Construção do modelo de regressão Linear 
mod1 = LinearRegression()
# Dados que queremos prever: PIB, chamaremos de Y
Y = treino.iloc[:,[2]]
# Dados que utilizaremos como possível causa: por exemplo, BRP chamaremos de X
X = treino.loc[:,['BRT','D1','D2','D3','D4','D5','D6','D7','D8','D9','D10','D11']]
mod1.fit(X,Y)

LinearRegression()

In [ ]:
# Preparação da base de teste para previsão utilizando o modelo de regressão
X_prev = teste.loc[:,['BRT','D1','D2','D3','D4','D5','D6','D7','D8','D9','D10','D11']]
Y_prev = mod1.predict(X_prev)

In [ ]:
Y_real = teste.iloc[:,[2]].to_numpy()

In [ ]:
# Calculo do erro de previsão
erro = Y_real - Y_prev
# Calculo do erro absoluto médio
erro_abs_medio = np.mean(abs(erro))
print(erro_abs_medio)
# Calculo do erro relativo (percentual)
erro_medio_perc = erro_abs_medio/np.mean(Y_real)
print(erro_medio_perc)

4.3201044827241155
0.02856662337090343

In [ ]:
OLS(Y,X).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                    PIB   R-squared (uncentered):                   0.999
Model:                            OLS   Adj. R-squared (uncentered):              0.999
Method:                 Least Squares   F-statistic:                          1.114e+04
Date:                Mon, 25 Apr 2022   Prob (F-statistic):                   1.43e-167
Time:                        21:36:22   Log-Likelihood:                         -345.67
No. Observations:                 125   AIC:                                      715.3
Df Residuals:                     113   BIC:                                      749.3
Df Model:                          12
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
BRT            0.9196      0.008    111.436      0.000       0.903       0.936
D1             3.0960      1.652      1.874      0.064      -0.177       6.369
D2            15.3399      1.564      9.811      0.000      12.242      18.438
D3            15.4002      1.600      9.625      0.000      12.230      18.570
D4            14.9133      1.589      9.383      0.000      11.764      18.062
D5            19.4794      1.592     12.234      0.000      16.325      22.634
D6            24.0410      1.602     15.011      0.000      20.868      27.214
D7            16.3452      1.659      9.852      0.000      13.058      19.632
D8            20.2430      1.641     12.333      0.000      16.991      23.495
D9            18.9865      1.636     11.603      0.000      15.745      22.228
D10           15.9254      1.660      9.591      0.000      12.636      19.215
D11           15.7119      1.650      9.521      0.000      12.442      18.981
==============================================================================
Omnibus:                        3.239   Durbin-Watson:                   0.698
Prob(Omnibus):                  0.198   Jarque-Bera (JB):                2.185
Skew:                          -0.124   Prob(JB):                        0.335
Kurtosis:                       2.402   Cond. No.                     1.29e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.29e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""